stages:
    - unit_tests
    - build_app

unit_tests:
    stage: unit_tests
    script:
        - xcodebuild clean -workspace EncodingConverter.xcworkspace -scheme EncodingConverter
        - xcodebuild test -workspace EncodingConverter.xcworkspace -scheme EncodingConverter

build_app:
    stage: build_app
    script:
        - xcodebuild clean -workspace EncodingConverter.xcworkspace -scheme EncodingConverter
        - xcodebuild build -workspace EncodingConverter.xcworkspace -scheme EncodingConverter -configuration Release
    artifacts:
        paths:
        - Build/Products/Release/EncodingConverter.app
        expire_in: 1 month
