stages:
    - build
build_project:
    stage: build
    script:
        - xcodebuild clean -project EncodingConverter.xcodeproj -scheme EncodingConverter
        - xcodebuild test -project EncodingConverter.xcodeproj -scheme EncodingConverter
