stages:
    - build
build_project:
    stage: build
    script:
        #- xcodebuild -project EncodingConverter.xcodeproj -list 
        #- xcodebuild clean -project EncodingConverter.xcodeproj -scheme EncodingConverterTests
        - xcodebuild test -project EncodingConverter.xcodeproj -scheme EncodingConverterTests
